### ISSUE TITLE
Remove 2 decimal place enforcement

### ISSUE THREAD

**Issue by owonwo** [Asyncpay-io/checkout-js#1]
https://github.com/Asyncpay-io/checkout-js/blob/85190e46ad562c78ab90b1852af9d4b4250d3ee4/src/index.ts#L154

This requires me to always ensure it's a 2dp on the frontend. Is there a way we could make it 1 or 2 digits?

**Comment by EricMcWinNer** [comment]
Yeah, we can. I'll make an update. Thanks.

**Comment by EricMcWinNer** [comment]
Fixed from `0.0.34`
